package com.example.yolo_homes.core

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

/** A single printed line: a left label and a right value. */
data class PdfRow(val label: String, val value: String, val emphasize: Boolean = false)

/**
 * Lightweight A4-ish PDF generator for receipts, water bills and reports.
 * Produces a file in cache and shares it via the app FileProvider.
 */
object PdfExporter {

    fun export(
        context: Context,
        fileName: String,
        title: String,
        subtitle: String,
        rows: List<PdfRow>
    ): File {
        val pageWidth = 595
        val pageHeight = 842
        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = doc.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply {
            color = Color.parseColor("#2563EB"); textSize = 26f; isFakeBoldText = true; isAntiAlias = true
        }
        val subPaint = Paint().apply { color = Color.parseColor("#64748B"); textSize = 13f; isAntiAlias = true }
        val labelPaint = Paint().apply { color = Color.parseColor("#64748B"); textSize = 14f; isAntiAlias = true }
        val valuePaint = Paint().apply { color = Color.parseColor("#0F172A"); textSize = 14f; isAntiAlias = true }
        val emphPaint = Paint().apply {
            color = Color.parseColor("#0F172A"); textSize = 18f; isFakeBoldText = true; isAntiAlias = true
        }
        val linePaint = Paint().apply { color = Color.parseColor("#E2E8F0"); strokeWidth = 1f }

        val left = 48f
        val right = pageWidth - 48f
        var y = 72f

        canvas.drawText(title, left, y, titlePaint)
        y += 22f
        canvas.drawText(subtitle, left, y, subPaint)
        y += 24f
        canvas.drawLine(left, y, right, y, linePaint)
        y += 28f

        rows.forEach { row ->
            val lp = if (row.emphasize) emphPaint else labelPaint
            val vp = if (row.emphasize) emphPaint else valuePaint
            canvas.drawText(row.label, left, y, lp)
            val w = vp.measureText(row.value)
            canvas.drawText(row.value, right - w, y, vp)
            y += if (row.emphasize) 32f else 26f
        }

        y += 16f
        canvas.drawLine(left, y, right, y, linePaint)
        y += 24f
        canvas.drawText("Generated by Yolo-Home's", left, y, subPaint)

        doc.finishPage(page)

        val file = File(context.cacheDir, fileName)
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }

    fun share(context: Context, file: File, label: String = "Share") {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, label).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
    }
}
