package com.example.yolo_homes.core

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

/** A single printed line: a left label and a right value. */
data class PdfRow(val label: String, val value: String, val emphasize: Boolean = false)

/**
 * Lightweight A4-ish PDF generator for receipts, water bills and reports.
 * Produces a file in cache and shares it via the app FileProvider.
 */
object PdfExporter {

    fun export(
        context: Context,
        fileName: String,
        title: String,
        subtitle: String,
        rows: List<PdfRow>
    ): File {
        val pageWidth = 595
        val pageHeight = 842
        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = doc.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply {
            color = Color.parseColor("#2563EB"); textSize = 26f; isFakeBoldText = true; isAntiAlias = true
        }
        val subPaint = Paint().apply { color = Color.parseColor("#64748B"); textSize = 13f; isAntiAlias = true }
        val labelPaint = Paint().apply { color = Color.parseColor("#64748B"); textSize = 14f; isAntiAlias = true }
        val valuePaint = Paint().apply { color = Color.parseColor("#0F172A"); textSize = 14f; isAntiAlias = true }
        val emphPaint = Paint().apply {
            color = Color.parseColor("#0F172A"); textSize = 18f; isFakeBoldText = true; isAntiAlias = true
        }
        val linePaint = Paint().apply { color = Color.parseColor("#E2E8F0"); strokeWidth = 1f }

        val left = 48f
        val right = pageWidth - 48f
        var y = 72f

        canvas.drawText(title, left, y, titlePaint)
        y += 22f
        canvas.drawText(subtitle, left, y, subPaint)
        y += 24f
        canvas.drawLine(left, y, right, y, linePaint)
        y += 28f

        rows.forEach { row ->
            val lp = if (row.emphasize) emphPaint else labelPaint
            val vp = if (row.emphasize) emphPaint else valuePaint
            canvas.drawText(row.label, left, y, lp)
            val w = vp.measureText(row.value)
            canvas.drawText(row.value, right - w, y, vp)
            y += if (row.emphasize) 32f else 26f
        }

        y += 16f
        canvas.drawLine(left, y, right, y, linePaint)
        y += 24f
        canvas.drawText("Generated by Yolo-Home's", left, y, subPaint)

        doc.finishPage(page)

        val file = File(context.cacheDir, fileName)
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }

    /**
     * Renders a multi-column table to PDF. Wide tables (>5 columns) switch to landscape and
     * column widths are sized proportionally to their content. Rows overflow onto extra pages,
     * each repeating the column header. Long cells are ellipsized to their column width.
     */
    fun exportTable(
        context: Context,
        fileName: String,
        title: String,
        subtitle: String,
        headers: List<String>,
        rows: List<List<String>>,
        footerNote: String = ""
    ): File {
        val landscape = headers.size > 5
        val pageWidth = if (landscape) 842 else 595
        val pageHeight = if (landscape) 595 else 842
        val margin = 36f
        val left = margin
        val right = pageWidth - margin
        val contentWidth = right - left
        val bottomLimit = pageHeight - 48f
        val cellPad = 6f

        val titlePaint = Paint().apply {
            color = Color.parseColor("#2563EB"); textSize = 22f; isFakeBoldText = true; isAntiAlias = true
        }
        val subPaint = Paint().apply { color = Color.parseColor("#64748B"); textSize = 11f; isAntiAlias = true }
        val headerTextPaint = Paint().apply {
            color = Color.WHITE; textSize = 10f; isFakeBoldText = true; isAntiAlias = true
        }
        val cellPaint = Paint().apply { color = Color.parseColor("#0F172A"); textSize = 9.5f; isAntiAlias = true }
        val headerBgPaint = Paint().apply { color = Color.parseColor("#2563EB") }
        val zebraPaint = Paint().apply { color = Color.parseColor("#F1F5F9") }
        val gridPaint = Paint().apply { color = Color.parseColor("#E2E8F0"); strokeWidth = 0.6f }
        val footPaint = Paint().apply { color = Color.parseColor("#94A3B8"); textSize = 10f; isAntiAlias = true }

        val colCount = headers.size
        val rawWidths = DoubleArray(colCount) { i ->
            var w = headerTextPaint.measureText(headers[i]).toDouble()
            rows.forEach { r -> if (i < r.size) w = maxOf(w, cellPaint.measureText(r[i]).toDouble()) }
            w + cellPad * 2
        }
        val totalRaw = rawWidths.sum().takeIf { it > 0.0 } ?: 1.0
        val widths = FloatArray(colCount) { (rawWidths[it] / totalRaw * contentWidth).toFloat() }
        val xOf = FloatArray(colCount) { i ->
            left + (0 until i).fold(0f) { acc, j -> acc + widths[j] }
        }

        val rowHeight = 18f
        val headerRowHeight = 22f

        fun ellipsize(text: String, paint: Paint, maxW: Float): String {
            if (paint.measureText(text) <= maxW) return text
            var t = text
            while (t.isNotEmpty() && paint.measureText("$t…") > maxW) t = t.dropLast(1)
            return "$t…"
        }

        val doc = PdfDocument()
        var pageNum = 0
        var page: PdfDocument.Page? = null
        var canvas = page?.canvas
        var y = 0f

        fun drawColumnHeader() {
            canvas?.drawRect(left, y, right, y + headerRowHeight, headerBgPaint)
            headers.forEachIndexed { i, h ->
                canvas?.drawText(ellipsize(h, headerTextPaint, widths[i] - cellPad * 2), xOf[i] + cellPad, y + headerRowHeight - 7f, headerTextPaint)
            }
            y += headerRowHeight
        }

        fun startPage(first: Boolean) {
            page?.let { doc.finishPage(it) }
            pageNum++
            page = doc.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum).create())
            canvas = page!!.canvas
            y = margin
            if (first) {
                canvas?.drawText(title, left, y + 6f, titlePaint)
                y += 26f
                if (subtitle.isNotBlank()) {
                    canvas?.drawText(subtitle, left, y, subPaint)
                    y += 16f
                }
                y += 6f
            }
            drawColumnHeader()
        }

        startPage(first = true)
        rows.forEachIndexed { index, row ->
            if (y + rowHeight > bottomLimit) startPage(first = false)
            if (index % 2 == 1) canvas?.drawRect(left, y, right, y + rowHeight, zebraPaint)
            row.forEachIndexed { i, cell ->
                if (i < colCount) {
                    canvas?.drawText(ellipsize(cell, cellPaint, widths[i] - cellPad * 2), xOf[i] + cellPad, y + rowHeight - 5.5f, cellPaint)
                }
            }
            canvas?.drawLine(left, y + rowHeight, right, y + rowHeight, gridPaint)
            y += rowHeight
        }

        y += 18f
        if (y > bottomLimit) startPage(first = false).also { y += 4f }
        canvas?.drawText(footerNote.ifBlank { "Generated by Yolo-Home's" }, left, y, footPaint)

        page?.let { doc.finishPage(it) }
        val file = File(context.cacheDir, fileName)
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }

    fun share(context: Context, file: File, label: String = "Share") {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, label).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
    }
}
